my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "qga42617.east-us-2.azure"

      # User/password auth
      user: "AyodejiOgunnaike"
      password: ""

      role: "ACCOUNTADMIN"
      database: "DATA_DB"
      warehouse: "COMPUTE_WH"
      schema: "DATA_SCHEMA"
      threads: 3
      client_session_keep_alive: False
      query_tag: null

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None
